### ISSUE TITLE
TypeError when opening profile

### ISSUE THREAD

**Issue by physanus** [SkyCryptWebsite/SkyCrypt#1851]
**Describe the bug**
When I try to open a users profile on my self installation, I sometimes get a TypeError. The error always occurs on certain profiles (seemingly the majority), on some other profiles it never occurs.

**Error Log**
This error appears when trying to open `/stats/Shiiyu`:
```
w1/stats_1675783374854.6193: stats page was called.
w1/stats_1675783374854.6193: getProfile called.
w1/stats_1675783374854.6193: getProfile returned. (44ms)
w1/stats_1675783374854.6193: getItems called.
w1/stats_1675783374854.6193: getItems returned. (1194ms)
w1/stats_1675783374854.6193: getStats called.
w1/stats_1675783374854.6193: an error has occurred.
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at getPets (file:///usr/src/main/src/lib.js:2576:79)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.getStats (file:///usr/src/main/src/lib.js:2388:17)
    at async file:///usr/src/main/src/app.js:272:24
```
When trying to access `Shiiyu`s Skyblock profile through the quick-link on the index page, I get the following error right in the [UI](https://i.imgur.com/hqy31nB.png):
`ERROR | Cannot read properties of undefined (reading 'toLowerCase')`
The application log is the same as before.

When trying to access `Cookie_Wookie_7`, I get the following application log. Note, that I added a debug message prefixed by `src/lib.js@L2797` at the mentioned file/line with the content `console.debug("src/lib.js@L2797: " + JSON.stringify(data));`. The last object does not contain the `tier`-tag.
```
w8/stats_1675783604350.4248: stats page was called.
w8/stats_1675783604350.4248: getProfile called.
w8/stats_1675783604350.4248: getProfile returned. (63ms)
w8/stats_1675783604350.4248: getItems called.
w8/stats_1675783604350.4248: getItems returned. (403ms)
w8/stats_1675783604350.4248: getStats called.
src/lib.js@L2797: {"_id":"63e240bea4c164c15d8ee26a","id":"PIGS_FOOT","category":"accessory","damage":3,"item_id":397,"material":"SKULL_ITEM","name":"Pig's Foot","npc_sell_price":1000,"soulbound":"COOP","stats":{"WALK_SPEED":1},"texture":"604faebefd0a8f721403e3142efecb83fbf4b7d1f705d0c9b44d91f0bf40127b","tier":"rare"}
src/lib.js@L2797: {"_id":"63e240bea4c164c15d8ee471","id":"ARTIFACT_POTION_AFFINITY","category":"accessory","damage":3,"item_id":397,"material":"SKULL_ITEM","name":"Potion Affinity Artifact","npc_sell_price":64000,"texture":"372466603bae9063ce7d94351103469beca3c5fe2b1e977e6427def37699ec9","tier":"rare"}
src/lib.js@L2797: {"_id":"63e240bda4c164c15d8eddc3","id":"WOLF_PAW","category":"accessory","damage":3,"item_id":397,"material":"SKULL_ITEM","name":"Wolf Paw","soulbound":"COOP","stats":{"WALK_SPEED":1},"texture":"7afd22704eeb5c67be649ddfe1da0c658158a7058d01739de31c94f6b9808869","tier":"uncommon"}
src/lib.js@L2797: {"_id":"63e240bda4c164c15d8edd4f","id":"HEALING_RING","category":"accessory","damage":3,"item_id":397,"material":"SKULL_ITEM","name":"Healing Ring","npc_sell_price":17000,"stats":{"vitality":10},"texture":"879fe7543ca1d5855e961514cff7e2728d2740ca3c33320d84dd053aea5dcb7d","tier":"uncommon"}
src/lib.js@L2797: {"_id":"63e240bea4c164c15d8ee8b5","id":"WOLF_RING","category":"accessory","damage":3,"item_id":397,"material":"SKULL_ITEM","name":"Wolf Ring","npc_sell_price":100,"texture":"f83a2aa9d3734b919ac24c9659e5e0f86ecafbf64d4788cfa433bbec189e8","tier":"rare"}
src/lib.js@L2797: {"_id":"63e240bea4c164c15d8ee5c3","id":"WOLF_TALISMAN","category":"accessory","damage":3,"item_id":397,"material":"SKULL_ITEM","name":"Wolf Talisman","npc_sell_price":50,"texture":"69d1d3113ec43ac2961dd59f28175fb4718873c6c448dfca8722317d67"}
file:///usr/src/main/src/lib.js:2798
        object.rarity = data.tier.toLowerCase();
                                  ^

TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at file:///usr/src/main/src/lib.js:2798:35
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.12.0
1675783604945: Worker 8 died with code 1  (pid:256)
1675783604964: Worker respawned with id 11 (pid:295)
Custom Resources loading started on worker11.
Custom Resources loading done. (worker11)
custom_resources_w11: 34.866ms
SkyBlock Stats running on http://localhost:80 (w11)
```
This time, the index page does not load/show an error; instead I get an error from my reverse-proxy (`502 Bad Gateway`).

When trying to access `ShinyPhanpy`, I get the following application log:
```
w7/stats_1675783481725.3656: stats page was called.
w7/stats_1675783481725.3656: getProfile called.
w7/stats_1675783481725.3656: getProfile returned. (796ms)
w7/stats_1675783481725.3656: getItems called.
w7/stats_1675783481725.3656: getItems returned. (1384ms)
w7/stats_1675783481725.3656: getStats called.
src/lib.js@L2797: {"_id":"63e240bea4c164c15d8ee6eb","id":"PARTY_HAT_CRAB","category":"accessory","damage":3,"item_id":397,"material":"SKULL_ITEM","museum":true,"name":"Crab Hat of Celebration","stats":{"MAGIC_FIND":1},"texture":"eb6c628a48f64160991544d2a784ec2ca09563e8d6da4919158273ababb91","tier":"special"}
TypeError: Cannot read properties of null (reading 'exp')
    at Module.getGuild (file:///usr/src/main/src/helper.js:342:69)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.getStats (file:///usr/src/main/src/lib.js:1807:18)
    at async file:///usr/src/main/src/app.js:272:24
w7/stats_1675783481725.3656: an error has occurred.
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at getPets (file:///usr/src/main/src/lib.js:2576:79)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.getStats (file:///usr/src/main/src/lib.js:2388:17)
    at async file:///usr/src/main/src/app.js:272:24
```

However, trying to access `/stats/LesbianCatgirl` redirects to `/stats/LesbianCatgirl/Lemon` and works just fine. My own profile also works without any issues.

**Developer Tools**
I use the container `node:18.12.0-slim` as a base.
- Node.js version: [e.g. v16, node v18]
`v18.12.0`
- OS: [e.g. Windows, Raspberry Pi OS]
`Debian 11`

**Additional context**
/

Initially I tried this by accident on the `development`-branch, but it seems that it also happens on the `production`-branch (which would make sense, since there are no additional commits on the `development`-branch at the time of testing; I didn't notice earlier).
Do you have any ideas where this error can come from?

**Comment by DuckySoLucky** [comment]
Heya, cannot reproduce. Can you join our support discord?

**Comment by metalcupcake5** [comment]
This happens due to items api missing tiers of some items, if your items database still has old data it won't throw an error. Bandaid fix is just to add the rarities manually, I think it was a couple of the fishing pet items at least iirc

**Comment by physanus** [comment]
For documentation purposes: Messaged on [Discord](https://discord.gg/cNgADv2kEQ) in [this Channel](https://discord.com/channels/738971489411399761/749694587689369711/1073610929540972565).
