### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Nim1com** [SkyCryptWebsite/SkyCrypt#234]
> SkyCrypt@1.0.0 start C:\Users\nikla\Desktop\GITHUB\SkyCrypt
> node init && node index

(node:169460) UnhandledPromiseRejectionWarning: C:\Users\nikla\Desktop\GITHUB\SkyCrypt\src\lib.js:514
            if(item.extra?.recombobulated)
                          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\nikla\Desktop\GITHUB\SkyCrypt\src\constants\leaderboards.js:4:26)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
(node:169460) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:169460) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
C:\Users\nikla\Desktop\GITHUB\SkyCrypt\src\app.js:81
        return cookie?.split(',').filter(uuid => /^[0-9a-f]+$/.test(uuid)) || []
                      ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\nikla\Desktop\GITHUB\SkyCrypt\index.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! SkyCrypt@1.0.0 start: `node init && node index`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the SkyCrypt@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nikla\AppData\Roaming\npm-cache\_logs\2021-01-13T12_32_17_146Z-debug.log

IS THE ERROR.

**Comment by MartinNemi03** [comment]
May I ask which version of Node you run the site on? There are some things that are supported by Node 14+, I think. Not sure about our Node version, I need to investigate further.

**Comment by metalcupcake5** [comment]
Optional chaining requires node 14 or above

**Comment by metalcupcake5** [comment]
Also, please follow the bug report template next time, thanks!

**Comment by Nim1com** [comment]
Yes I will use the bug template and It was the node ver problem.
